name: Android Release

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Retrieve Version
        run: |
          chmod +x gradlew
          echo "version_name=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Verify Tag matches Version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          APP_VERSION="v${{ env.version_name }}"
          
          if [ "$TAG_NAME" != "$APP_VERSION" ]; then
            echo "::error::Tag name ($TAG_NAME) does not match Gradle version ($APP_VERSION)!"
            exit 1
          fi
          echo "Tag and version match: $TAG_NAME"

      - name: Checkout keystore repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: Fill credentials
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          PLAZA_API: ${{ secrets.PLAZA_API }}
        run: |
          echo -e "SENTRY_DSN=$SENTRY_DSN\nPLAZA_API=$PLAZA_API" > plaza.properties

      - name: Build release artifacts
        run: |
          ./gradlew fetchAndEmbedView
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Rename release file
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/NightwavePlaza-${{ env.version_name }}.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Upload artifact
          path: app/build/outputs/apk/release/NightwavePlaza-${{ env.version_name }}.apk

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.version_name }}
          files: app/build/outputs/apk/release/NightwavePlaza-${{ env.version_name }}.apk
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
